//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int AdminID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string AdminType { get; set; }
        public int UserID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
