//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        public int WorkerID { get; set; }
        public int YearsOfService { get; set; }
        public string Salary { get; set; }
        public string EducationDegree { get; set; }
        public int UserID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
