//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWorker
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public string Residence { get; set; }
        public string MarriageStatus { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public int YearsOfService { get; set; }
        public string Salary { get; set; }
        public string EducationDegree { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public int WorkerID { get; set; }
    }
}
